// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieManagementWeb_API.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MovieManagementWeb_API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250624142548_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Actor", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(100)
                    .HasColumnType("character varying(100)");

                b.HasKey("Id");

                b.ToTable("Actors");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.ActorMovie", b =>
            {
                b.Property<int>("ActorId")
                    .HasColumnType("integer");

                b.Property<int>("MovieId")
                    .HasColumnType("integer");

                b.HasKey("ActorId", "MovieId");

                b.HasIndex("MovieId");

                b.ToTable("ActorMovies");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Genre", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(50)
                    .HasColumnType("character varying(50)");

                b.HasKey("Id");

                b.ToTable("Genres");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Movie", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("CarouselImage")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Cast")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("CreatedByUsername")
                    .HasColumnType("text");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Director")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<int?>("Duration")
                    .HasColumnType("integer");

                b.Property<string>("EditedByUsername")
                    .HasColumnType("text");

                b.PrimitiveCollection<List<string>>("Format")
                    .IsRequired()
                    .HasColumnType("text[]");

                b.Property<string>("Image")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("ProductionCompany")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("RatingCode")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime>("ReleaseDate")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Status")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Subtitle")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(255)
                    .HasColumnType("character varying(255)");

                b.Property<string>("TrailerLink")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.HasKey("Id");

                b.ToTable("Movies");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.MovieGenre", b =>
            {
                b.Property<int>("MovieId")
                    .HasColumnType("integer");

                b.Property<int>("GenreId")
                    .HasColumnType("integer");

                b.HasKey("MovieId", "GenreId");

                b.HasIndex("GenreId");

                b.ToTable("MovieGenres");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Showtime", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<DateTime>("Date")
                    .HasColumnType("timestamp with time zone");

                b.Property<int>("MovieId")
                    .HasColumnType("integer");

                b.Property<string>("RoomName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Time")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.HasIndex("MovieId");

                b.ToTable("Showtimes");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.User", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("integer");

                NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                b.Property<string>("Address")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<DateTime?>("BirthDate")
                    .HasColumnType("timestamp without time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Gender")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("IdCard")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<bool>("IsLocked")
                    .HasColumnType("boolean");

                b.Property<string>("Password")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("PhoneNumber")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Username")
                    .IsRequired()
                    .HasColumnType("text");

                b.HasKey("Id");

                b.ToTable("Users");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.ActorMovie", b =>
            {
                b.HasOne("MovieManagementWeb_API.Models.Entities.Actor", "Actor")
                    .WithMany("ActorMovies")
                    .HasForeignKey("ActorId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MovieManagementWeb_API.Models.Entities.Movie", "Movie")
                    .WithMany("ActorMovies")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Actor");

                b.Navigation("Movie");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.MovieGenre", b =>
            {
                b.HasOne("MovieManagementWeb_API.Models.Entities.Genre", "Genre")
                    .WithMany("MovieGenres")
                    .HasForeignKey("GenreId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.HasOne("MovieManagementWeb_API.Models.Entities.Movie", "Movie")
                    .WithMany("MovieGenres")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Genre");

                b.Navigation("Movie");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Showtime", b =>
            {
                b.HasOne("MovieManagementWeb_API.Models.Entities.Movie", "Movie")
                    .WithMany("Showtimes")
                    .HasForeignKey("MovieId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("Movie");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Actor", b =>
            {
                b.Navigation("ActorMovies");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Genre", b =>
            {
                b.Navigation("MovieGenres");
            });

            modelBuilder.Entity("MovieManagementWeb_API.Models.Entities.Movie", b =>
            {
                b.Navigation("ActorMovies");

                b.Navigation("MovieGenres");

                b.Navigation("Showtimes");
            });
#pragma warning restore 612, 618
        }
    }
}
